# Generated by Django 6.0.6 on 2026-10-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('subject', models.CharField(max_length=160, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='leido')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('tagline', models.CharField(max_length=140, verbose_name='eslogan')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio mensual')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio anual')),
                ('currency', models.CharField(default='USD', max_length=4, verbose_name='moneda')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='etiqueta')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'ordering': ['order', 'price_monthly'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('full_name', models.CharField(max_length=120, verbose_name='nombre completo')),
                ('role', models.CharField(max_length=120, verbose_name='cargo')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('initials', models.CharField(help_text='Se usa como avatar de respaldo.', max_length=4, verbose_name='iniciales')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
            ],
            options={
                'verbose_name': 'integrante',
                'verbose_name_plural': 'integrantes',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='detalle')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='destacada')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'caracteristica de plan',
                'verbose_name_plural': 'caracteristicas de plan',
                'ordering': ['plan_id', 'order', 'id'],
                'abstract': False,
            },
        ),
    ]
